feat/add contribute button in home page
walnuthq/starkflare pull request #21
Opened 2024-05-23 12:20 UTC by BlackStarkGoku

2024-05-28 22:13 UTC, melnikga requested changes
Hi, please make the following changes:
-Remove the changes from button.tsx
-Return the default variant and size to the button
-Change the text above the button to "Have ideas to make Starkflare better?"

2024-05-28 22:13 UTC, melnikga commented on src/components/ContributeBox.tsx
> +        Have ideas to make cairovm.codes better?
Change the text above the button to "Have ideas to make Starkflare better?"

2024-05-28 22:13 UTC, melnikga commented on src/components/ContributeBox.tsx
> +        <Button size={"padded"} variant={"contribute"}>
Return the default variant and size to the button

2024-05-28 22:13 UTC, melnikga commented on src/components/ui/button.tsx
Remove the changes from button.tsx

2024-05-31 10:52 UTC, melnikga approved these changes
LGTM!

2024-05-31 15:38 UTC, barabanovro approved these changes

2024-05-31 15:38 UTC, merged