Timeline selection dropdown PR
walnuthq/starkflare pull request #22
Opened 2024-05-24 16:11 UTC by Joy-Adah

Added a disabled dropdown to the header with a 7 days label.

2024-05-28 21:37 UTC, melnikga requested changes
Hi, there is no need to make up the Select component from scratch. Use ready-made components from shadcn. There is a component called Select.

2024-05-29 17:31 UTC, melnikga requested changes
Hi, the tooltip also needs to be imported from shadcn

2024-05-29 17:31 UTC, melnikga commented on src/components/header.tsx
> +            <div className="absolute top-full left-1/2 transform -translate-x-1/2 mt-2 w-48 bg-gray-700 text-white text-center rounded-lg py-2 opacity-0 transition-opacity duration-300 group-hover:op
Import tolltip from shadcn

2024-05-30 22:18 UTC, melnikga requested changes
Hi, when the project starts, errors appear that are visible in the console and displayed on the page. This is related to incorrect nesting of components and the absence of the 'asChild' attribute in TooltipTrigger. The last screenshot shows the correct structure.
Error:
![image](https://github.com/walnuthq/starkflare/assets/91109124/88ae25cf-878a-4d08-bc97-1764de4ff8d0)
The right structure:
![image](https://github.com/walnuthq/starkflare/assets/91109124/844fb67e-b3d5-461a-8e68-ccc39f1bcb04)

2024-05-31 06:35 UTC, Joy-Adah commented
Hi @melnikga I'll have it implemented

2024-05-31 11:47 UTC, Joy-Adah commented
hi @melnikga i have implemented the suggested changes

2024-05-31 15:53 UTC, melnikga approved these changes
LGTM!

2024-06-03 20:51 UTC, melnikga commented
@Joy-Adah resolve branch conflicts please

2024-06-04 12:41 UTC, barabanovro approved these changes

2024-06-04 12:41 UTC, merged